language: objective-c
osx_image: xcode9
rvm: 2.4

cache:
  cocoapods: true

install:
- gem install cocoapods xcpretty
- pod repo update
- pod install
- brew install jq

env:
  - SCHEME=iOSTests
  - SCHEME=tvOSTests
  - SCHEME=macOSTests

script:
  - export DESTINATION="$(./scripts/destination.sh $SCHEME)"
  - xcrun simctl list
  - set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace Tests.xcworkspace -scheme "$SCHEME" -destination "$DESTINATION" build test | xcpretty
