lane :test do
  xcversion(version: '9')
  FileUtils.cd ".." do
    ["iOSTests", "tvOSTests", "macOSTests"].each do |scheme|
      destination = Actions.sh "./scripts/destination.sh #{scheme}"
      destination.strip!
      command = "set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace Tests.xcworkspace -scheme #{scheme} -derivedDataPath build -destination \"#{destination}\" build test | xcpretty"
      FastlaneCore::CommandExecutor.execute(command: command, print_all: true, print_command: true)
    end
  end
end

lane :release do |options|
  cocoapods
  test
  bump = options[:bump]
  bump ||= 'patch'
  new_version(type: bump, increase: true, path: podspec)
  tag(message: '')
  pod_push
end

lane :patch do |options|
  new_version(type: 'patch', increase: true, path: podspec)
end

lane :minor do |options|
  new_version(type: 'minor', increase: true, path: podspec)
end

lane :major do |options|
  new_version(type: 'major', increase: true, path: podspec)
end

private_lane :new_version do |options|
  if options[:version]
    version_bump_podspec(
      path: options[:path],
      version_number: options[:version]
    )
  else
    type = options[:type] ? options[:type] : 'patch'
    version_bump_podspec(
      path: options[:path],
      bump_type: type
    )
  end

  if options[:increase]
    message = "Increased #{options[:path]} version #{lane_context[SharedValues::PODSPEC_VERSION_NUMBER]}"
  else
    message = "Changed #{options[:path]} version #{lane_context[SharedValues::PODSPEC_VERSION_NUMBER]}"
  end

  git_commit(
    path: options[:path],
    message: message
  )
end

lane :tag do |options|
  message = options[:message]
  message ||= UI.input("Enter release message: ")
  version = version_get_podspec(path: podspec)

  sh("git tag -am '#{message}' '#{version}'")
  sh("git push --tags")
end

lane :lint do
  pod_lib_lint(
    use_bundle_exec: true,
    verbose: true,
    fail_fast: true
  )
end

private_lane :podspec do
  'DateUtilities.podspec'
end
