lane :test do
  ENV['SCAN_DERIVED_DATA_PATH'] = 'build'
  Actions.sh "rm -rf ../build"
  scan(scheme: 'iOSTests', device: 'iPhone 7')
  Actions.sh "rm -rf ../build"
  scan(scheme: 'tvOSTests', device: 'Apple TV 1080p')
  Actions.sh "rm -rf ../build"
  Actions.sh "env NSUnbufferedIO=YES xcodebuild -workspace ../Tests.xcworkspace -scheme macOSTests -derivedDataPath ../build build test | xcpretty"
end

lane :release do |options|
  cocoapods
  test
  bump = options[:bump]
  bump ||= 'patch'
  new_version(type: bump, increase: true, path: podspec)
  tag(message: '')
  push
end

lane :patch do |options|
  new_version(type: 'patch', increase: true, path: podspec)
end

lane :minor do |options|
  new_version(type: 'minor', increase: true, path: podspec)
end

lane :major do |options|
  new_version(type: 'major', increase: true, path: podspec)
end

private_lane :new_version do |options|
  if options[:version]
    version_bump_podspec(
      path: options[:path],
      version_number: options[:version]
    )
  else
    type = options[:type] ? options[:type] : 'patch'
    version_bump_podspec(
      path: options[:path],
      bump_type: type
    )
  end

  if options[:increase]
    message = "Increased #{options[:path]} version #{lane_context[SharedValues::PODSPEC_VERSION_NUMBER]}"
  else
    message = "Changed #{options[:path]} version #{lane_context[SharedValues::PODSPEC_VERSION_NUMBER]}"
  end

  git_commit(
    path: options[:path],
    message: message
  )
end

lane :tag do |options|
  message = options[:message]
  message ||= UI.input("Enter release message: ")
  version = version_get_podspec(path: podspec)

  sh("git tag -am '#{message}' '#{version}'")
  sh("git push --tags")
end

lane :lint do
  pod_lib_lint(
    use_bundle_exec: true,
    verbose: true,
    fail_fast: true    
  )
end

private_lane :podspec do
  'DateUtilities.podspec'
end
