name: tests

on: [push]

jobs:
  build:
    runs-on: macOS-10.14
    strategy:
      matrix:
        scheme: [iOSTests, tvOSTests, macOSTests]

    steps:
      - uses: actions/checkout@v1
      - name: Prepare environment
        run: |
          bundle install
          bundle exec pod install --repo-update
      - name: Test
        run: |
          xcrun simctl list
          set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace Tests.xcworkspace -scheme "${{ matrix.scheme }}" -destination "$(./scripts/destination.sh ${{ matrix.scheme }})" build test | xcpretty
