name: tests

on: [push]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        os:
          [
            { "type": "iOS", "name": "iOS 12.4" },
            { "type": "tvOS", "name": "tvOS 12.4" },
            { "type": "iOS", "name": "iOS 13.3" },
            { "type": "tvOS", "name": "tvOS 13.3" },
            { "type": "macOS", "name": "macOS 10.15" },
          ]

    steps:
      - uses: actions/checkout@v1
      - name: Prepare environment
        run: |
          bundle install
          bundle exec pod install --repo-update
      - name: Choose device
        id: choose-device
        uses: chipp/choose-device@v1
        env:
          DEVELOPER_DIR: /Applications/Xcode_11.3.app
        with:
          os: ${{ matrix.os.name }}
      - name: Test
        env:
          DEVELOPER_DIR: /Applications/Xcode_11.3.app
        run: |
          xcrun simctl list
          set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace Tests.xcworkspace -scheme "${{ matrix.os.type }}Tests" -destination "${{ steps.choose-device.outputs.destination }}" build test | xcpretty
